/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4;

/**
 *
 * @author crist
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jifAgregarMateria.hide();
        jifInscribir.hide();
        jifagregarAlumno.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        escritorio = new javax.swing.JDesktopPane();
        jifagregarAlumno = new javax.swing.JInternalFrame();
        btnAASalir = new javax.swing.JButton();
        jifInscribir = new javax.swing.JInternalFrame();
        btnISalir = new javax.swing.JButton();
        jifAgregarMateria = new javax.swing.JInternalFrame();
        btnAMSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAlumnos = new javax.swing.JMenu();
        mitmAgregarAlumno = new javax.swing.JMenuItem();
        mMaterias = new javax.swing.JMenu();
        mitmAgregarMateria = new javax.swing.JMenuItem();
        mInscripcion = new javax.swing.JMenu();
        mitmInscribir = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifagregarAlumno.setVisible(true);

        btnAASalir.setText("Salir");
        btnAASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAASalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifagregarAlumnoLayout = new javax.swing.GroupLayout(jifagregarAlumno.getContentPane());
        jifagregarAlumno.getContentPane().setLayout(jifagregarAlumnoLayout);
        jifagregarAlumnoLayout.setHorizontalGroup(
            jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(btnAASalir)
                .addContainerGap())
        );
        jifagregarAlumnoLayout.setVerticalGroup(
            jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                .addComponent(btnAASalir)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jifInscribir.setVisible(true);

        btnISalir.setText("Salir");
        btnISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnISalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifInscribirLayout = new javax.swing.GroupLayout(jifInscribir.getContentPane());
        jifInscribir.getContentPane().setLayout(jifInscribirLayout);
        jifInscribirLayout.setHorizontalGroup(
            jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifInscribirLayout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(btnISalir))
        );
        jifInscribirLayout.setVerticalGroup(
            jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifInscribirLayout.createSequentialGroup()
                .addComponent(btnISalir)
                .addGap(0, 311, Short.MAX_VALUE))
        );

        jifAgregarMateria.setVisible(true);

        btnAMSalir.setText("Salir");
        btnAMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifAgregarMateriaLayout = new javax.swing.GroupLayout(jifAgregarMateria.getContentPane());
        jifAgregarMateria.getContentPane().setLayout(jifAgregarMateriaLayout);
        jifAgregarMateriaLayout.setHorizontalGroup(
            jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifAgregarMateriaLayout.createSequentialGroup()
                .addGap(0, 272, Short.MAX_VALUE)
                .addComponent(btnAMSalir))
        );
        jifAgregarMateriaLayout.setVerticalGroup(
            jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifAgregarMateriaLayout.createSequentialGroup()
                .addComponent(btnAMSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        escritorio.setLayer(jifagregarAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jifInscribir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jifAgregarMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jifagregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jifAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jifInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jifagregarAlumno)
                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jifInscribir)
                        .addComponent(jifAgregarMateria)))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        mAlumnos.setText("VistaAlumnos");

        mitmAgregarAlumno.setText("Agregar Alumno");
        mitmAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmAgregarAlumnoActionPerformed(evt);
            }
        });
        mAlumnos.add(mitmAgregarAlumno);

        jMenuBar1.add(mAlumnos);

        mMaterias.setText("VistaMaterias");

        mitmAgregarMateria.setText("Agregar Materia");
        mitmAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmAgregarMateriaActionPerformed(evt);
            }
        });
        mMaterias.add(mitmAgregarMateria);

        jMenuBar1.add(mMaterias);

        mInscripcion.setText("V.Inscripcion");

        mitmInscribir.setText("Inscribir");
        mitmInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmInscribirActionPerformed(evt);
            }
        });
        mInscripcion.add(mitmInscribir);

        jMenuBar1.add(mInscripcion);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitmAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        jifagregarAlumno.show();

    }//GEN-LAST:event_mitmAgregarAlumnoActionPerformed

    private void mitmAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmAgregarMateriaActionPerformed
        // TODO add your handling code here:
        jifAgregarMateria.show();

    }//GEN-LAST:event_mitmAgregarMateriaActionPerformed

    private void mitmInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmInscribirActionPerformed
        // TODO add your handling code here:
        jifInscribir.show();

    }//GEN-LAST:event_mitmInscribirActionPerformed

    private void btnAASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAASalirActionPerformed
        // TODO add your handling code here:
        jifagregarAlumno.hide();
    }//GEN-LAST:event_btnAASalirActionPerformed

    private void btnAMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMSalirActionPerformed
        // TODO add your handling code here:
        jifAgregarMateria.hide();
    }//GEN-LAST:event_btnAMSalirActionPerformed

    private void btnISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISalirActionPerformed
        // TODO add your handling code here:
        jifInscribir.hide();
    }//GEN-LAST:event_btnISalirActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAASalir;
    private javax.swing.JButton btnAMSalir;
    private javax.swing.JButton btnISalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JInternalFrame jifAgregarMateria;
    private javax.swing.JInternalFrame jifInscribir;
    private javax.swing.JInternalFrame jifagregarAlumno;
    private javax.swing.JMenu mAlumnos;
    private javax.swing.JMenu mInscripcion;
    private javax.swing.JMenu mMaterias;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem mitmAgregarAlumno;
    private javax.swing.JMenuItem mitmAgregarMateria;
    private javax.swing.JMenuItem mitmInscribir;
    // End of variables declaration//GEN-END:variables
}
