/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.util.HashSet;
import javax.swing.JOptionPane;
import tp4.Alumno;
import tp4.Colegio;
import tp4.Materia;

/**
 *
 * @author crist
 */
public class Principal extends javax.swing.JFrame {
    
    public static HashSet<Alumno> alumnos = new HashSet<>();
    public static HashSet<Materia> materias = new HashSet<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jifAgregarMateria.hide();
        jifInscribir.hide();
        jifagregarAlumno.hide();
        
        alumnos = Colegio.getAlumnos();
        materias = Colegio.getMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        escritorio = new javax.swing.JDesktopPane();
        jifagregarAlumno = new javax.swing.JInternalFrame();
        btnAASalir = new javax.swing.JButton();
        btnAANuevo = new javax.swing.JButton();
        btnAAGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inptLegajo = new javax.swing.JTextField();
        inptApellido = new javax.swing.JTextField();
        inptNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jifInscribir = new javax.swing.JInternalFrame();
        btnISalir = new javax.swing.JButton();
        btnIInscribir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        cbAlumnos = new javax.swing.JComboBox<>();
        jifAgregarMateria = new javax.swing.JInternalFrame();
        btnAMSalir = new javax.swing.JButton();
        btnAMNuevo = new javax.swing.JButton();
        btnAMGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inptCodMat = new javax.swing.JTextField();
        inptNomMat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inptAnio = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAlumnos = new javax.swing.JMenu();
        mitmAgregarAlumno = new javax.swing.JMenuItem();
        mMaterias = new javax.swing.JMenu();
        mitmAgregarMateria = new javax.swing.JMenuItem();
        mInscripcion = new javax.swing.JMenu();
        mitmInscribir = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifagregarAlumno.setPreferredSize(new java.awt.Dimension(300, 300));
        jifagregarAlumno.setVisible(true);

        btnAASalir.setText("Salir");
        btnAASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAASalirActionPerformed(evt);
            }
        });

        btnAANuevo.setText("Nuevo");

        btnAAGuardar.setText("Guardar");
        btnAAGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAAGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("LEGAJO:");

        jLabel2.setText("APELLIDO:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Formulario de Alumnos");

        javax.swing.GroupLayout jifagregarAlumnoLayout = new javax.swing.GroupLayout(jifagregarAlumno.getContentPane());
        jifagregarAlumno.getContentPane().setLayout(jifagregarAlumnoLayout);
        jifagregarAlumnoLayout.setHorizontalGroup(
            jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifagregarAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAAGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAANuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAASalir)
                .addContainerGap())
            .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inptApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifagregarAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inptLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifagregarAlumnoLayout.setVerticalGroup(
            jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifagregarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inptLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inptApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jifagregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAASalir)
                    .addComponent(btnAANuevo)
                    .addComponent(btnAAGuardar))
                .addContainerGap())
        );

        jifInscribir.setPreferredSize(new java.awt.Dimension(300, 300));
        jifInscribir.setVisible(true);

        btnISalir.setText("Salir");
        btnISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnISalirActionPerformed(evt);
            }
        });

        btnIInscribir.setText("Inscribir");
        btnIInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIInscribirActionPerformed(evt);
            }
        });

        jLabel9.setText("ELIJA MATERIA:");

        jLabel10.setText("ELIJA ALUMNO:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Formulario de Inscripción");

        cbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbMaterias.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbMateriasPropertyChange(evt);
            }
        });

        cbAlumnos.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifInscribirLayout = new javax.swing.GroupLayout(jifInscribir.getContentPane());
        jifInscribir.getContentPane().setLayout(jifInscribirLayout);
        jifInscribirLayout.setHorizontalGroup(
            jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifInscribirLayout.createSequentialGroup()
                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifInscribirLayout.createSequentialGroup()
                        .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jifInscribirLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIInscribir))
                            .addGroup(jifInscribirLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnISalir))
                    .addGroup(jifInscribirLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jifInscribirLayout.setVerticalGroup(
            jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifInscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(44, 44, 44)
                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jifInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnISalir)
                    .addComponent(btnIInscribir))
                .addContainerGap())
        );

        jifAgregarMateria.setPreferredSize(new java.awt.Dimension(300, 300));
        jifAgregarMateria.setVisible(true);

        btnAMSalir.setText("Salir");
        btnAMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMSalirActionPerformed(evt);
            }
        });

        btnAMNuevo.setText("Nuevo");

        btnAMGuardar.setText("Guardar");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Formulario de Alumnos");

        jLabel6.setText("CODIGO DE MATERIA:");

        jLabel7.setText("NOMBRE DE LA MATERIA:");

        jLabel8.setText("AÑO AL QUE PERTENECE:");

        javax.swing.GroupLayout jifAgregarMateriaLayout = new javax.swing.GroupLayout(jifAgregarMateria.getContentPane());
        jifAgregarMateria.getContentPane().setLayout(jifAgregarMateriaLayout);
        jifAgregarMateriaLayout.setHorizontalGroup(
            jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifAgregarMateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inptAnio)
                    .addComponent(inptCodMat)
                    .addComponent(inptNomMat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(jifAgregarMateriaLayout.createSequentialGroup()
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifAgregarMateriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAMGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAMNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAMSalir)
                        .addGap(9, 9, 9)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jifAgregarMateriaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        jifAgregarMateriaLayout.setVerticalGroup(
            jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifAgregarMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inptCodMat))
                .addGap(26, 26, 26)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inptNomMat))
                .addGap(30, 30, 30)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inptAnio))
                .addGap(63, 63, 63)
                .addGroup(jifAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAMSalir)
                    .addComponent(btnAMNuevo)
                    .addComponent(btnAMGuardar))
                .addContainerGap())
        );

        escritorio.setLayer(jifagregarAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jifInscribir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jifAgregarMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jifagregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jifAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jifInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jifAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jifagregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jifInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mAlumnos.setText("VistaAlumnos");

        mitmAgregarAlumno.setText("Agregar Alumno");
        mitmAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmAgregarAlumnoActionPerformed(evt);
            }
        });
        mAlumnos.add(mitmAgregarAlumno);

        jMenuBar1.add(mAlumnos);

        mMaterias.setText("VistaMaterias");

        mitmAgregarMateria.setText("Agregar Materia");
        mitmAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmAgregarMateriaActionPerformed(evt);
            }
        });
        mMaterias.add(mitmAgregarMateria);

        jMenuBar1.add(mMaterias);

        mInscripcion.setText("V.Inscripcion");

        mitmInscribir.setText("Inscribir");
        mitmInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmInscribirActionPerformed(evt);
            }
        });
        mInscripcion.add(mitmInscribir);

        jMenuBar1.add(mInscripcion);

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitmAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        jifagregarAlumno.show();

    }//GEN-LAST:event_mitmAgregarAlumnoActionPerformed

    private void mitmAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmAgregarMateriaActionPerformed
        // TODO add your handling code here:
        jifAgregarMateria.show();

    }//GEN-LAST:event_mitmAgregarMateriaActionPerformed

    private void mitmInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmInscribirActionPerformed
        // TODO add your handling code here:
        jifInscribir.show();
        
       
        
        for (Alumno a : alumnos){
            cbAlumnos.addItem(a);
        }
        for (Materia m : materias){
            cbMaterias.addItem(m);
        }

    }//GEN-LAST:event_mitmInscribirActionPerformed

    private void btnAASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAASalirActionPerformed
        // TODO add your handling code here:
        jifagregarAlumno.hide();
    }//GEN-LAST:event_btnAASalirActionPerformed

    private void btnAMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMSalirActionPerformed
        // TODO add your handling code here:
        jifAgregarMateria.hide();
    }//GEN-LAST:event_btnAMSalirActionPerformed

    private void btnISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISalirActionPerformed
        // TODO add your handling code here:
        jifInscribir.hide();
    }//GEN-LAST:event_btnISalirActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mSalirActionPerformed

    private void btnAAGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAAGuardarActionPerformed
        // TODO add your handling code here:
        try {
        int legajo = Integer.parseInt(inptLegajo.getText());
        String  apellido = inptApellido.getText();
        String  nombre = inptNombre.getText();
        
        
        
      } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(this, "Ingrese un numero valido pliss");
        }
           
    }//GEN-LAST:event_btnAAGuardarActionPerformed

    private void cbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlumnosActionPerformed

    private void cbMateriasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbMateriasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateriasPropertyChange

    private void btnIInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIInscribirActionPerformed
        // TODO add your handling code here:
        Alumno  alSelect = (Alumno) cbAlumnos.getSelectedItem();
        Materia  matSelect = (Materia) cbMaterias.getSelectedItem();
        
        if (alSelect != null && matSelect != null) {
            String res = alSelect.agregarMateria(matSelect);
            JOptionPane.showMessageDialog(this,"El alumno "+ alSelect + " "+ res);
        } 
    }//GEN-LAST:event_btnIInscribirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAAGuardar;
    private javax.swing.JButton btnAANuevo;
    private javax.swing.JButton btnAASalir;
    private javax.swing.JButton btnAMGuardar;
    private javax.swing.JButton btnAMNuevo;
    private javax.swing.JButton btnAMSalir;
    private javax.swing.JButton btnIInscribir;
    private javax.swing.JButton btnISalir;
    private javax.swing.JComboBox<Alumno> cbAlumnos;
    private javax.swing.JComboBox<Materia> cbMaterias;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JTextField inptAnio;
    private javax.swing.JTextField inptApellido;
    private javax.swing.JTextField inptCodMat;
    private javax.swing.JTextField inptLegajo;
    private javax.swing.JTextField inptNomMat;
    private javax.swing.JTextField inptNombre;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JInternalFrame jifAgregarMateria;
    private javax.swing.JInternalFrame jifInscribir;
    private javax.swing.JInternalFrame jifagregarAlumno;
    private javax.swing.JMenu mAlumnos;
    private javax.swing.JMenu mInscripcion;
    private javax.swing.JMenu mMaterias;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem mitmAgregarAlumno;
    private javax.swing.JMenuItem mitmAgregarMateria;
    private javax.swing.JMenuItem mitmInscribir;
    // End of variables declaration//GEN-END:variables
}
